trigger:
- main

pool:
  name: 'Azure Linux Agent'
  demands:
    - agent.name -equals ALA

steps:

- task: JavaToolInstaller@0
  inputs:
    versionSpec: "11"
    jdkArchitectureOption: x64
    jdkSourceOption: LocalDirectory
    jdkFile: "/builds/openjdk-11.0.2_linux-x64_bin.tar.gz"
    jdkDestinationDirectory: "/builds/binaries/externals"
    cleanDestinationDirectory: true

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m -XX:MaxPermSize=512m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.17'  # Adjust to your Java version (e.g., 17, 21)
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    testRunTitle: 'Maven Tests'
    goals: 'package'