trigger:
- main

pool:
  name: 'Azure Linux Agent'
  demands:
    - agent.name -equals ALA

steps:
- task: JavaToolInstaller@0
  displayName: 'Set up JDK 21'
  inputs:
    versionSpec: '21'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- script: |
    echo $JAVA_HOME
    java -version
  displayName: 'Debug JDK Setup'

- task: Maven@4
  displayName: 'Maven Build'
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'Path'
    jdkDirectory: $(JAVA_HOME)
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
